export const AGREE = 'AGREE'

//ESTIMATOR
export const GET_CONDITIONS = 'GET_CONDITIONS' // also used in: [Survey]
export const GET_SEVERITIES = 'GET_SEVERITIES' // also used in: [Survey]
export const GET_DOSE = 'GET_DOSE'
export const UPDATE_STEPS = 'UPDATE_STEPS'
export const SELECT_CONDITION = 'SELECT_CONDITION' // also used in: [Survey]
export const SELECT_SEVERITY = 'SELECT_SEVERITY' // also used in: [Survey]
export const UPDATE_VALIDATION_ERR = 'UPDATE_VALIDATION_ERR' // also used in: [ALL]

//PRODUCTS
export const GET_PRODUCTS = 'GET_PRODUCTS' // also used in: [Measure]
export const UPDATE_FILTERED_PRODUCTS = 'UPDATE_FILTERED_PRODUCTS'
export const UPDATE_QUIZ_STEPS = 'UPDATE_QUIZ_STEPS'
export const SELECT_DOSE = 'SELECT_DOSE' // also used in: [Measure, Survey]
export const SELECT_IMPORTANCE = 'SELECT_IMPORTANCE'
export const SELECT_QUALITY = 'SELECT_QUALITY'

//MEASURE
export const UPDATE_MEASURE_STEPS = 'UPDATE_MEASURE_STEPS'
export const SELECT_DEVICE = 'SELECT_DEVICE'
export const SELECT_BRAND = 'SELECT_BRAND'
export const SELECT_PRODUCT = 'SELECT_PRODUCT'
export const SELECT_SIZE = 'SELECT_SIZE'
export const SELECT_PRODUCT_MG = 'SELECT_PRODUCT_MG'

//SURVEY
export const UPDATE_SURVEY_STEPS = 'UPDATE_SURVEY_STEPS'
export const INPUT_WEIGHT = 'INPUT_WEIGHT'
export const SELECT_PROFESSIONAL_HELP = 'SELECT_PROFESSIONAL_HELP'
export const SELECT_OTHER_MEDICATION = 'SELECT_OTHER_MEDICATION'
export const UPDATE_OTHER_MEDICATION_INPUT = 'UPDATE_OTHER_MEDICATION_INPUT'
export const SELECT_DOSE_DURATION = 'SELECT_DOSE_DURATION'
export const SELECT_IMPROVEMENT = 'SELECT_IMPROVEMENT'
export const INPUT_ELABORATE = 'ELABORATE'
export const VERIFY_SURVEY = 'VERIFY_SURVEY'

//ADDING PRODUCTS
export const UPDATE_ADDING_PRODUCTS_STEPS = 'UPDATE_ADDING_PRODUCTS_STEPS'
export const UPDATE_INPUT_COMPANY_NAME = 'UPDATE_INPUT_COMPANY_NAME'
export const SELECT_INVOLVEMENT = 'SELECT_INVOLVEMENT'
export const UPDATE_INPUT_EMAIL = 'UPDATE_INPUT_EMAIL' // also used in: [Estimator, Measure]
export const UPDATE_INPUT_WEBSITE = 'UPDATE_INPUT_WEBSITE'

//ADVERTISING PRODUCTS
export const UPDATE_ADVERTISING_STEPS = 'UPDATE_ADVERTISING_STEPS'
export const UPDATE_INPUT_COMPANY_NAME_ADVERTISING = 'UPDATE_INPUT_COMPANY_NAME_ADVERTISING'
export const SELECT_INVOLVEMENT_ADVERTISING = 'SELECT_INVOLVEMENT_ADVERTISING'
export const UPDATE_INPUT_FIRST_NAME = 'UPDATE_INPUT_FIRST_NAME'
export const UPDATE_INPUT_LAST_NAME = 'UPDATE_INPUT_LAST_NAME'
export const UPDATE_INPUT_EMAIL_ADVERTISING = 'UPDATE_INPUT_EMAIL_ADVERTISING'
export const UPDATE_INPUT_PHONE = 'UPDATE_INPUT_PHONE'
export const UPDATE_INPUT_SHOP_WEBSITE = 'UPDATE_INPUT_SHOP_WEBSITE'
export const UPDATE_INPUT_QUALITY_LINK = 'UPDATE_INPUT_QUALITY_LINK'
export const SELECT_AFFILIATE_STATUS = 'SELECT_AFFILIATE_STATUS'
export const UPDATE_AFFILIATE_APP_LINK = 'UPDATE_AFFILIATE_APP_LINK'
export const UPDATE_INPUT_BRAND_DESC = 'UPDATE_INPUT_BRAND_DESC'

//FEEDBACK
export const UPDATE_OVERALL_RATING = 'UPDATE_OVERALL_RATING'
export const UPDATE_EASE_OF_USE_RATING = 'UPDATE_EASE_OF_USE_RATING'
export const UPDATE_HELPFULNESS_RATING = 'UPDATE_HELPFULNESS_RATING'
export const UPDATE_INPUT_MOST_LIKE = 'UPDATE_INPUT_MOST_LIKE'
export const UPDATE_INPUT_LEAST_LIKE = 'UPDATE_INPUT_LEAST_LIKE'
export const UPDATE_INPUT_SUGGESTIONS = 'UPDATE_INPUT_SUGGESTIONS'
export const UPDATE_INPUT_FEEDBACK_EMAIL = 'UPDATE_INPUT_FEEDBACK_EMAIL'