export const AGREE = 'AGREE'

//ESTIMATOR
export const GET_CONDITIONS = 'GET_CONDITIONS' // also used in: [Survey]
export const GET_SEVERITIES = 'GET_SEVERITIES' // also used in: [Survey]
export const GET_DOSE = 'GET_DOSE'
export const UPDATE_STEPS = 'UPDATE_STEPS'
export const SELECT_CONDITION = 'SELECT_CONDITION' // also used in: [Survey]
export const SELECT_SEVERITY = 'SELECT_SEVERITY'

//PRODUCTS
export const GET_PRODUCTS = 'GET_PRODUCTS' // also used in: [Measure]
export const UPDATE_FILTERED_PRODUCTS = 'UPDATE_FILTERED_PRODUCTS'
export const UPDATE_QUIZ_STEPS = 'UPDATE_QUIZ_STEPS'
export const SELECT_DOSE = 'SELECT_DOSE' // also used in: [Measure, Survey]
export const SELECT_IMPORTANCE = 'SELECT_IMPORTANCE'
export const SELECT_QUALITY = 'SELECT_QUALITY'

//MEASURE
export const UPDATE_MEASURE_STEPS = 'UPDATE_MEASURE_STEPS'
export const SELECT_DEVICE = 'SELECT_DEVICE'
export const SELECT_BRAND = 'SELECT_BRAND'
export const SELECT_PRODUCT = 'SELECT_PRODUCT'
export const SELECT_SIZE = 'SELECT_SIZE'
export const SELECT_PRODUCT_MG = 'SELECT_PRODUCT_MG'

//SURVEY
export const UPDATE_SURVEY_STEPS = 'UPDATE_SURVEY_STEPS'
export const INPUT_WEIGHT = 'INPUT_WEIGHT'
export const SELECT_PROFESSIONAL_HELP = 'SELECT_PROFESSIONAL_HELP'
export const SELECT_OTHER_MEDICATION = 'SELECT_OTHER_MEDICATION'
export const SELECT_DOSE_DURATION = 'SELECT_DOSE_DURATION'
export const SELECT_IMPROVEMENT = 'SELECT_IMPROVEMENT'
export const INPUT_ELABORATE = 'ELABORATE'
export const VERIFY_SURVEY = 'VERIFY_SURVEY'